// <auto-generated />
using GaSoft.EFCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GaSoft.EFCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420182341_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GaSoft.Domain.Entities.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_departamentos");

                    b.ToTable("departamentos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Gestão das finanças",
                            Nome = "Financeiro"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Promoção de produtos",
                            Nome = "Marketing"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Recursos Humanos",
                            Nome = "RH"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Atendimento ao cliente",
                            Nome = "Suporte"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Tecnologia da Informação",
                            Nome = "TI"
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Gestão de Vendas",
                            Nome = "Vendas"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
