// <auto-generated />
using System;
using GaSoft.EFCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GaSoft.EFCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423155230_IncluiFuncionarioEDetalhe")]
    partial class IncluiFuncionarioEDetalhe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GaSoft.Domain.Entities.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_departamentos");

                    b.ToTable("departamentos", (string)null);
                });

            modelBuilder.Entity("GaSoft.Domain.Entities.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cargo");

                    b.Property<DateOnly>("DataContratacao")
                        .HasColumnType("date")
                        .HasColumnName("data_contratacao");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int")
                        .HasColumnName("departamento_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Salario")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("salario");

                    b.HasKey("Id")
                        .HasName("pk_funcionarios");

                    b.HasIndex("DepartamentoId")
                        .HasDatabaseName("ix_funcionarios_departamento_id");

                    b.ToTable("funcionarios", (string)null);
                });

            modelBuilder.Entity("GaSoft.Domain.Entities.FuncionarioDetalhe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cpf");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("celular");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("EnderecoResidencial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("endereco_residencial");

                    b.Property<int>("Escolaridade")
                        .HasColumnType("int")
                        .HasColumnName("escolaridade");

                    b.Property<int>("EstadoCivil")
                        .HasColumnType("int")
                        .HasColumnName("estado_civil");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("foto");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int")
                        .HasColumnName("funcionario_id");

                    b.Property<int>("Genero")
                        .HasColumnType("int")
                        .HasColumnName("genero");

                    b.Property<string>("Nacionalidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nacionalidade");

                    b.HasKey("Id")
                        .HasName("pk_funcionario_detalhes");

                    b.HasIndex("FuncionarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_funcionario_detalhes_funcionario_id");

                    b.ToTable("funcionario_detalhes", (string)null);
                });

            modelBuilder.Entity("GaSoft.Domain.Entities.Funcionario", b =>
                {
                    b.HasOne("GaSoft.Domain.Entities.Departamento", "Departamento")
                        .WithMany("Funcionarios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_funcionarios_departamentos_departamento_id");

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("GaSoft.Domain.Entities.FuncionarioDetalhe", b =>
                {
                    b.HasOne("GaSoft.Domain.Entities.Funcionario", "Funcionario")
                        .WithOne("FuncionarioDetalhe")
                        .HasForeignKey("GaSoft.Domain.Entities.FuncionarioDetalhe", "FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_funcionario_detalhes_funcionarios_funcionario_id");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("GaSoft.Domain.Entities.Departamento", b =>
                {
                    b.Navigation("Funcionarios");
                });

            modelBuilder.Entity("GaSoft.Domain.Entities.Funcionario", b =>
                {
                    b.Navigation("FuncionarioDetalhe");
                });
#pragma warning restore 612, 618
        }
    }
}
