// <auto-generated />
using System;
using GaSoft.EFCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GaSoft.EFCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423160751_SeedDataMigration")]
    partial class SeedDataMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GaSoft.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ativo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_clientes_email");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_clientes_nome");

                    b.ToTable("clientes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Email = "abroad@email.com",
                            Nome = "Grupo ABroad SA",
                            Telefone = "55-11 9980-0099"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Email = "abcconstru@email.com",
                            Nome = "Construtora ABC",
                            Telefone = "55-31 8957-1022"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Email = "edufuture@email.com",
                            Nome = "EduFuture Corp.",
                            Telefone = "55-11 8750-4422"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Email = "innovators@email.com",
                            Nome = "Tech Innovators Ltda",
                            Telefone = "55-11 9950-9622"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = false,
                            Email = "healtsolutions@email.com",
                            Nome = "Health Solutions Inc.",
                            Telefone = "55-21 9852-9655"
                        });
                });

            modelBuilder.Entity("GaSoft.Domain.Entities.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_departamentos");

                    b.ToTable("departamentos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Gestão das finanças",
                            Nome = "Financeiro"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Promoção de produtos",
                            Nome = "Marketing"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Recursos Humanos",
                            Nome = "RH"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Atendimento ao cliente",
                            Nome = "Suporte"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Tecnologia da Informação",
                            Nome = "TI"
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Gestão de Vendas",
                            Nome = "Vendas"
                        });
                });

            modelBuilder.Entity("GaSoft.Domain.Entities.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cargo");

                    b.Property<DateOnly>("DataContratacao")
                        .HasColumnType("date")
                        .HasColumnName("data_contratacao");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int")
                        .HasColumnName("departamento_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Salario")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("salario");

                    b.HasKey("Id")
                        .HasName("pk_funcionarios");

                    b.HasIndex("DepartamentoId")
                        .HasDatabaseName("ix_funcionarios_departamento_id");

                    b.ToTable("funcionarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cargo = "Gerente de Finanças",
                            DataContratacao = new DateOnly(2023, 1, 15),
                            DepartamentoId = 1,
                            Nome = "João da Silva",
                            Salario = 5250.00m
                        },
                        new
                        {
                            Id = 2,
                            Cargo = "Analista Financeiro",
                            DataContratacao = new DateOnly(2021, 11, 10),
                            DepartamentoId = 1,
                            Nome = "Carlos Pereira",
                            Salario = 4500.00m
                        },
                        new
                        {
                            Id = 3,
                            Cargo = "Analista Financeiro",
                            DataContratacao = new DateOnly(2022, 2, 15),
                            DepartamentoId = 1,
                            Nome = "Ana Souza",
                            Salario = 4300.00m
                        },
                        new
                        {
                            Id = 4,
                            Cargo = "Técnico em Contabilidade",
                            DataContratacao = new DateOnly(2023, 4, 5),
                            DepartamentoId = 1,
                            Nome = "Fernanda Oliveira",
                            Salario = 3400.00m
                        },
                        new
                        {
                            Id = 5,
                            Cargo = "Técnico em Contabilidade",
                            DataContratacao = new DateOnly(2023, 7, 18),
                            DepartamentoId = 1,
                            Nome = "José Santos",
                            Salario = 3400.00m
                        },
                        new
                        {
                            Id = 6,
                            Cargo = "Analista de Marketing",
                            DataContratacao = new DateOnly(2021, 11, 10),
                            DepartamentoId = 2,
                            Nome = "Lucia Benitez",
                            Salario = 4500.00m
                        },
                        new
                        {
                            Id = 7,
                            Cargo = "Analista de Marketing",
                            DataContratacao = new DateOnly(2022, 8, 22),
                            DepartamentoId = 2,
                            Nome = "Pedro Cardoso",
                            Salario = 4100.00m
                        },
                        new
                        {
                            Id = 8,
                            Cargo = "Gerente de Marketing",
                            DataContratacao = new DateOnly(2023, 3, 1),
                            DepartamentoId = 2,
                            Nome = "Fabiana Costa",
                            Salario = 5100.00m
                        },
                        new
                        {
                            Id = 9,
                            Cargo = "Analista de Recursos Humanos",
                            DataContratacao = new DateOnly(2021, 9, 20),
                            DepartamentoId = 3,
                            Nome = "Roberto Ferreira",
                            Salario = 3400.00m
                        },
                        new
                        {
                            Id = 10,
                            Cargo = "Gerente de Recursos Humanos",
                            DataContratacao = new DateOnly(2022, 3, 10),
                            DepartamentoId = 3,
                            Nome = "Beatriz Almeida",
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = 11,
                            Cargo = "Analista de Recursos Humanos",
                            DataContratacao = new DateOnly(2023, 5, 5),
                            DepartamentoId = 3,
                            Nome = "Mariana Dias",
                            Salario = 3000.00m
                        },
                        new
                        {
                            Id = 12,
                            Cargo = "Analista de Suporte",
                            DataContratacao = new DateOnly(2022, 6, 15),
                            DepartamentoId = 4,
                            Nome = "Juliana Mendes",
                            Salario = 3200.00m
                        },
                        new
                        {
                            Id = 13,
                            Cargo = "Gerente de Suporte",
                            DataContratacao = new DateOnly(2022, 8, 22),
                            DepartamentoId = 4,
                            Nome = "Rafael Souza",
                            Salario = 5800.00m
                        },
                        new
                        {
                            Id = 14,
                            Cargo = "Analista de Suporte",
                            DataContratacao = new DateOnly(2023, 1, 1),
                            DepartamentoId = 4,
                            Nome = "Bruno Costa",
                            Salario = 4000.00m
                        },
                        new
                        {
                            Id = 15,
                            Cargo = "Analista de Suporte",
                            DataContratacao = new DateOnly(2023, 3, 10),
                            DepartamentoId = 4,
                            Nome = "Aline Dias",
                            Salario = 3900.00m
                        },
                        new
                        {
                            Id = 16,
                            Cargo = "Analista de TI",
                            DataContratacao = new DateOnly(2021, 11, 10),
                            DepartamentoId = 5,
                            Nome = "Felix Carvalho",
                            Salario = 4800.00m
                        },
                        new
                        {
                            Id = 17,
                            Cargo = "Programador Senior",
                            DataContratacao = new DateOnly(2022, 6, 5),
                            DepartamentoId = 5,
                            Nome = "Gustavo Almeida",
                            Salario = 4500.00m
                        },
                        new
                        {
                            Id = 18,
                            Cargo = "Analista de TI",
                            DataContratacao = new DateOnly(2021, 5, 18),
                            DepartamentoId = 5,
                            Nome = "Renata Silva",
                            Salario = 4800.00m
                        },
                        new
                        {
                            Id = 19,
                            Cargo = "Gerente de TI",
                            DataContratacao = new DateOnly(2023, 4, 15),
                            DepartamentoId = 5,
                            Nome = "Thiago Souza",
                            Salario = 6600.00m
                        },
                        new
                        {
                            Id = 20,
                            Cargo = "Engenheiro de Software",
                            DataContratacao = new DateOnly(2023, 5, 10),
                            DepartamentoId = 5,
                            Nome = "Vanessa Oliveira",
                            Salario = 5250.00m
                        },
                        new
                        {
                            Id = 21,
                            Cargo = "Analista de TI",
                            DataContratacao = new DateOnly(2023, 8, 1),
                            DepartamentoId = 5,
                            Nome = "Leandro Pereira",
                            Salario = 4800.00m
                        },
                        new
                        {
                            Id = 22,
                            Cargo = "Programador Junior",
                            DataContratacao = new DateOnly(2021, 11, 10),
                            DepartamentoId = 5,
                            Nome = "Fernando Carvalho",
                            Salario = 2500.00m
                        },
                        new
                        {
                            Id = 23,
                            Cargo = "Programador Junior",
                            DataContratacao = new DateOnly(2023, 3, 13),
                            DepartamentoId = 5,
                            Nome = "Gilberto Almeida",
                            Salario = 2300.00m
                        },
                        new
                        {
                            Id = 24,
                            Cargo = "Programador Junior",
                            DataContratacao = new DateOnly(2022, 5, 20),
                            DepartamentoId = 5,
                            Nome = "Renata Silva",
                            Salario = 2800.00m
                        },
                        new
                        {
                            Id = 25,
                            Cargo = "Programador Junior",
                            DataContratacao = new DateOnly(2023, 4, 5),
                            DepartamentoId = 5,
                            Nome = "Tamirez Souza",
                            Salario = 2600.00m
                        },
                        new
                        {
                            Id = 26,
                            Cargo = "Arquiteta de Software",
                            DataContratacao = new DateOnly(2023, 5, 10),
                            DepartamentoId = 5,
                            Nome = "Vanessa Oliveira",
                            Salario = 5000.00m
                        },
                        new
                        {
                            Id = 27,
                            Cargo = "Programador Senior",
                            DataContratacao = new DateOnly(2023, 8, 1),
                            DepartamentoId = 5,
                            Nome = "Leonardo Pereira",
                            Salario = 5500.00m
                        },
                        new
                        {
                            Id = 28,
                            Cargo = "Programador Senior",
                            DataContratacao = new DateOnly(2021, 10, 10),
                            DepartamentoId = 5,
                            Nome = "Maria Benitez",
                            Salario = 5100.00m
                        },
                        new
                        {
                            Id = 29,
                            Cargo = "Programador Senior",
                            DataContratacao = new DateOnly(2022, 2, 11),
                            DepartamentoId = 5,
                            Nome = "Ricardo Pereira",
                            Salario = 4500.00m
                        },
                        new
                        {
                            Id = 30,
                            Cargo = "Programador Senior",
                            DataContratacao = new DateOnly(2023, 8, 1),
                            DepartamentoId = 5,
                            Nome = "Paula Santos",
                            Salario = 3200.00m
                        },
                        new
                        {
                            Id = 31,
                            Cargo = "Programador Senior",
                            DataContratacao = new DateOnly(2023, 8, 1),
                            DepartamentoId = 5,
                            Nome = "Leonardo Pereira",
                            Salario = 4650.00m
                        },
                        new
                        {
                            Id = 32,
                            Cargo = "Arquiteto de Software",
                            DataContratacao = new DateOnly(2021, 10, 10),
                            DepartamentoId = 5,
                            Nome = "Maria Benitez",
                            Salario = 5200.00m
                        },
                        new
                        {
                            Id = 33,
                            Cargo = "Programador Senior",
                            DataContratacao = new DateOnly(2022, 2, 10),
                            DepartamentoId = 5,
                            Nome = "Reinaldo Pedreira",
                            Salario = 4500.00m
                        },
                        new
                        {
                            Id = 34,
                            Cargo = "Programador Senior",
                            DataContratacao = new DateOnly(2022, 4, 20),
                            DepartamentoId = 5,
                            Nome = "Helena Cintra",
                            Salario = 4600.00m
                        },
                        new
                        {
                            Id = 35,
                            Cargo = "Programador Senior",
                            DataContratacao = new DateOnly(2021, 9, 20),
                            DepartamentoId = 5,
                            Nome = "Carlos Santos",
                            Salario = 4500.00m
                        },
                        new
                        {
                            Id = 36,
                            Cargo = "Programador Senior",
                            DataContratacao = new DateOnly(2023, 8, 1),
                            DepartamentoId = 5,
                            Nome = "Leonardo Ramirez",
                            Salario = 4500.00m
                        },
                        new
                        {
                            Id = 37,
                            Cargo = "Engenheiro de Testes",
                            DataContratacao = new DateOnly(2021, 10, 10),
                            DepartamentoId = 5,
                            Nome = "Amanda Sanches",
                            Salario = 5200.00m
                        },
                        new
                        {
                            Id = 38,
                            Cargo = "Engenheiro de Testes",
                            DataContratacao = new DateOnly(2023, 2, 5),
                            DepartamentoId = 5,
                            Nome = "Rodrigo Pereira",
                            Salario = 4800.00m
                        },
                        new
                        {
                            Id = 39,
                            Cargo = "Engenheiro de Testes",
                            DataContratacao = new DateOnly(2022, 5, 20),
                            DepartamentoId = 5,
                            Nome = "Alicia Santos",
                            Salario = 5300.00m
                        },
                        new
                        {
                            Id = 40,
                            Cargo = "Arquiteto de Software",
                            DataContratacao = new DateOnly(2022, 6, 20),
                            DepartamentoId = 5,
                            Nome = "Paulo Mellado",
                            Salario = 5800.00m
                        },
                        new
                        {
                            Id = 41,
                            Cargo = "Gerente de Vendas",
                            DataContratacao = new DateOnly(2021, 10, 10),
                            DepartamentoId = 6,
                            Nome = "Marta Carvalho",
                            Salario = 5200.00m
                        },
                        new
                        {
                            Id = 42,
                            Cargo = "Representante de Vendas",
                            DataContratacao = new DateOnly(2022, 2, 15),
                            DepartamentoId = 6,
                            Nome = "Ricardo Sanches",
                            Salario = 4500.00m
                        },
                        new
                        {
                            Id = 43,
                            Cargo = "Assistente de Vendas",
                            DataContratacao = new DateOnly(2022, 5, 20),
                            DepartamentoId = 6,
                            Nome = "Patrícia Santos",
                            Salario = 3200.00m
                        },
                        new
                        {
                            Id = 44,
                            Cargo = "Representante de Vendas",
                            DataContratacao = new DateOnly(2022, 7, 18),
                            DepartamentoId = 6,
                            Nome = "Alberto Lima",
                            Salario = 4800.00m
                        },
                        new
                        {
                            Id = 45,
                            Cargo = "Assistente de Vendas",
                            DataContratacao = new DateOnly(2023, 6, 10),
                            DepartamentoId = 6,
                            Nome = "Rogério Oliveira",
                            Salario = 3700.00m
                        });
                });

            modelBuilder.Entity("GaSoft.Domain.Entities.FuncionarioDetalhe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cpf");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("celular");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("EnderecoResidencial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("endereco_residencial");

                    b.Property<int>("Escolaridade")
                        .HasColumnType("int")
                        .HasColumnName("escolaridade");

                    b.Property<int>("EstadoCivil")
                        .HasColumnType("int")
                        .HasColumnName("estado_civil");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("foto");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int")
                        .HasColumnName("funcionario_id");

                    b.Property<int>("Genero")
                        .HasColumnType("int")
                        .HasColumnName("genero");

                    b.Property<string>("Nacionalidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nacionalidade");

                    b.HasKey("Id")
                        .HasName("pk_funcionario_detalhes");

                    b.HasIndex("FuncionarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_funcionario_detalhes_funcionario_id");

                    b.ToTable("funcionario_detalhes", (string)null);
                });

            modelBuilder.Entity("GaSoft.Domain.Entities.FuncionarioProjeto", b =>
                {
                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int")
                        .HasColumnName("funcionario_id");

                    b.Property<int>("ProjetoId")
                        .HasColumnType("int")
                        .HasColumnName("projeto_id");

                    b.Property<int>("HorasTrabalhadas")
                        .HasColumnType("int")
                        .HasColumnName("horas_trabalhadas");

                    b.HasKey("FuncionarioId", "ProjetoId")
                        .HasName("pk_funcionarios_projetos");

                    b.HasIndex("ProjetoId")
                        .HasDatabaseName("ix_funcionarios_projetos_projeto_id");

                    b.ToTable("funcionarios_projetos", (string)null);

                    b.HasData(
                        new
                        {
                            FuncionarioId = 16,
                            ProjetoId = 1,
                            HorasTrabalhadas = 15
                        },
                        new
                        {
                            FuncionarioId = 24,
                            ProjetoId = 1,
                            HorasTrabalhadas = 15
                        },
                        new
                        {
                            FuncionarioId = 18,
                            ProjetoId = 2,
                            HorasTrabalhadas = 20
                        },
                        new
                        {
                            FuncionarioId = 22,
                            ProjetoId = 2,
                            HorasTrabalhadas = 25
                        },
                        new
                        {
                            FuncionarioId = 19,
                            ProjetoId = 3,
                            HorasTrabalhadas = 30
                        },
                        new
                        {
                            FuncionarioId = 29,
                            ProjetoId = 3,
                            HorasTrabalhadas = 40
                        },
                        new
                        {
                            FuncionarioId = 28,
                            ProjetoId = 3,
                            HorasTrabalhadas = 28
                        },
                        new
                        {
                            FuncionarioId = 19,
                            ProjetoId = 4,
                            HorasTrabalhadas = 18
                        },
                        new
                        {
                            FuncionarioId = 25,
                            ProjetoId = 4,
                            HorasTrabalhadas = 22
                        },
                        new
                        {
                            FuncionarioId = 32,
                            ProjetoId = 4,
                            HorasTrabalhadas = 15
                        },
                        new
                        {
                            FuncionarioId = 21,
                            ProjetoId = 5,
                            HorasTrabalhadas = 30
                        },
                        new
                        {
                            FuncionarioId = 20,
                            ProjetoId = 5,
                            HorasTrabalhadas = 27
                        },
                        new
                        {
                            FuncionarioId = 33,
                            ProjetoId = 5,
                            HorasTrabalhadas = 42
                        },
                        new
                        {
                            FuncionarioId = 34,
                            ProjetoId = 5,
                            HorasTrabalhadas = 40
                        },
                        new
                        {
                            FuncionarioId = 35,
                            ProjetoId = 5,
                            HorasTrabalhadas = 38
                        },
                        new
                        {
                            FuncionarioId = 36,
                            ProjetoId = 5,
                            HorasTrabalhadas = 42
                        },
                        new
                        {
                            FuncionarioId = 38,
                            ProjetoId = 5,
                            HorasTrabalhadas = 20
                        },
                        new
                        {
                            FuncionarioId = 19,
                            ProjetoId = 6,
                            HorasTrabalhadas = 5
                        },
                        new
                        {
                            FuncionarioId = 22,
                            ProjetoId = 6,
                            HorasTrabalhadas = 10
                        },
                        new
                        {
                            FuncionarioId = 19,
                            ProjetoId = 7,
                            HorasTrabalhadas = 48
                        },
                        new
                        {
                            FuncionarioId = 24,
                            ProjetoId = 7,
                            HorasTrabalhadas = 44
                        },
                        new
                        {
                            FuncionarioId = 17,
                            ProjetoId = 7,
                            HorasTrabalhadas = 52
                        },
                        new
                        {
                            FuncionarioId = 35,
                            ProjetoId = 7,
                            HorasTrabalhadas = 40
                        },
                        new
                        {
                            FuncionarioId = 36,
                            ProjetoId = 7,
                            HorasTrabalhadas = 38
                        },
                        new
                        {
                            FuncionarioId = 37,
                            ProjetoId = 7,
                            HorasTrabalhadas = 30
                        },
                        new
                        {
                            FuncionarioId = 27,
                            ProjetoId = 7,
                            HorasTrabalhadas = 44
                        },
                        new
                        {
                            FuncionarioId = 40,
                            ProjetoId = 7,
                            HorasTrabalhadas = 42
                        });
                });

            modelBuilder.Entity("GaSoft.Domain.Entities.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_inicio");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Orcamento")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("orcamento");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_projetos");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_projetos_cliente_id");

                    b.ToTable("projetos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 2,
                            DataAtualizacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2023, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Descrição do Projeto A",
                            Nome = "Projeto A",
                            Orcamento = 1000000m,
                            Status = 3
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 1,
                            DataAtualizacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2023, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Descrição do Projeto B",
                            Nome = "Projeto B",
                            Orcamento = 2000000m,
                            Status = 5
                        },
                        new
                        {
                            Id = 3,
                            ClienteId = 5,
                            DataAtualizacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Descrição do Projeto C",
                            Nome = "Projeto C",
                            Orcamento = 3000000m,
                            Status = 10
                        },
                        new
                        {
                            Id = 4,
                            ClienteId = 3,
                            DataAtualizacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2023, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Descrição do Projeto D",
                            Nome = "Projeto D",
                            Orcamento = 4000000m,
                            Status = 10
                        },
                        new
                        {
                            Id = 5,
                            ClienteId = 4,
                            DataAtualizacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2023, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Descrição do Projeto E",
                            Nome = "Projeto E",
                            Orcamento = 5000000m,
                            Status = 20
                        },
                        new
                        {
                            Id = 6,
                            ClienteId = 1,
                            DataAtualizacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2023, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Descrição do Projeto F",
                            Nome = "Projeto F",
                            Orcamento = 6000000m,
                            Status = -1
                        },
                        new
                        {
                            Id = 7,
                            ClienteId = 3,
                            DataAtualizacao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Descrição do Projeto G",
                            Nome = "Projeto G",
                            Orcamento = 9000000m,
                            Status = 20
                        });
                });

            modelBuilder.Entity("GaSoft.Domain.Entities.Funcionario", b =>
                {
                    b.HasOne("GaSoft.Domain.Entities.Departamento", "Departamento")
                        .WithMany("Funcionarios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_funcionarios_departamentos_departamento_id");

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("GaSoft.Domain.Entities.FuncionarioDetalhe", b =>
                {
                    b.HasOne("GaSoft.Domain.Entities.Funcionario", "Funcionario")
                        .WithOne("FuncionarioDetalhe")
                        .HasForeignKey("GaSoft.Domain.Entities.FuncionarioDetalhe", "FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_funcionario_detalhes_funcionarios_funcionario_id");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("GaSoft.Domain.Entities.FuncionarioProjeto", b =>
                {
                    b.HasOne("GaSoft.Domain.Entities.Funcionario", "Funcionario")
                        .WithMany("FuncionariosProjetos")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_funcionarios_projetos_funcionarios_funcionario_id");

                    b.HasOne("GaSoft.Domain.Entities.Projeto", "Projeto")
                        .WithMany("FuncionariosProjetos")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_funcionarios_projetos_projetos_projeto_id");

                    b.Navigation("Funcionario");

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("GaSoft.Domain.Entities.Projeto", b =>
                {
                    b.HasOne("GaSoft.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Projetos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_projetos_clientes_cliente_id");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("GaSoft.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Projetos");
                });

            modelBuilder.Entity("GaSoft.Domain.Entities.Departamento", b =>
                {
                    b.Navigation("Funcionarios");
                });

            modelBuilder.Entity("GaSoft.Domain.Entities.Funcionario", b =>
                {
                    b.Navigation("FuncionarioDetalhe");

                    b.Navigation("FuncionariosProjetos");
                });

            modelBuilder.Entity("GaSoft.Domain.Entities.Projeto", b =>
                {
                    b.Navigation("FuncionariosProjetos");
                });
#pragma warning restore 612, 618
        }
    }
}
